# Generated by Django 4.2.1 on 2023-06-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax", options={"verbose_name_plural": "tax"},
        ),
    ]
