# Generated by Django 4.2.1 on 2023-06-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0005_alter_openinghour_options_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="vendors",
            field=models.ManyToManyField(blank=True, to="vendor.vendor"),
        ),
    ]
